/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardObservabilityRouteImport } from './routes/dashboard/observability'
import { Route as DashboardMailRouteImport } from './routes/dashboard/mail'
import { Route as DashboardInboxRouteImport } from './routes/dashboard/inbox'
import { Route as DashboardCreationRouteImport } from './routes/dashboard/creation'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard/calendar'
import { Route as DashboardBookmarksRouteImport } from './routes/dashboard/bookmarks'
import { Route as DashboardBoardRouteImport } from './routes/dashboard/board'
import { Route as DashboardAgentsRouteImport } from './routes/dashboard/agents'
import { Route as ApiTurnstileVerifyRouteImport } from './routes/api.turnstile-verify'
import { Route as ApiGithubStarsRouteImport } from './routes/api.github-stars'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardObservabilityRoute = DashboardObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMailRoute = DashboardMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInboxRoute = DashboardInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreationRoute = DashboardCreationRouteImport.update({
  id: '/creation',
  path: '/creation',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookmarksRoute = DashboardBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBoardRoute = DashboardBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsRoute = DashboardAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiTurnstileVerifyRoute = ApiTurnstileVerifyRouteImport.update({
  id: '/api/turnstile-verify',
  path: '/api/turnstile-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubStarsRoute = ApiGithubStarsRouteImport.update({
  id: '/api/github-stars',
  path: '/api/github-stars',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/github-stars': typeof ApiGithubStarsRoute
  '/api/turnstile-verify': typeof ApiTurnstileVerifyRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/board': typeof DashboardBoardRoute
  '/dashboard/bookmarks': typeof DashboardBookmarksRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/creation': typeof DashboardCreationRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/mail': typeof DashboardMailRoute
  '/dashboard/observability': typeof DashboardObservabilityRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/github-stars': typeof ApiGithubStarsRoute
  '/api/turnstile-verify': typeof ApiTurnstileVerifyRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/board': typeof DashboardBoardRoute
  '/dashboard/bookmarks': typeof DashboardBookmarksRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/creation': typeof DashboardCreationRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/mail': typeof DashboardMailRoute
  '/dashboard/observability': typeof DashboardObservabilityRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/github-stars': typeof ApiGithubStarsRoute
  '/api/turnstile-verify': typeof ApiTurnstileVerifyRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/board': typeof DashboardBoardRoute
  '/dashboard/bookmarks': typeof DashboardBookmarksRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/creation': typeof DashboardCreationRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/mail': typeof DashboardMailRoute
  '/dashboard/observability': typeof DashboardObservabilityRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/changelog'
    | '/dashboard'
    | '/docs'
    | '/pricing'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/sso-callback'
    | '/terms'
    | '/api/chat'
    | '/api/github-stars'
    | '/api/turnstile-verify'
    | '/dashboard/agents'
    | '/dashboard/board'
    | '/dashboard/bookmarks'
    | '/dashboard/calendar'
    | '/dashboard/creation'
    | '/dashboard/inbox'
    | '/dashboard/mail'
    | '/dashboard/observability'
    | '/dashboard/'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/changelog'
    | '/docs'
    | '/pricing'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/sso-callback'
    | '/terms'
    | '/api/chat'
    | '/api/github-stars'
    | '/api/turnstile-verify'
    | '/dashboard/agents'
    | '/dashboard/board'
    | '/dashboard/bookmarks'
    | '/dashboard/calendar'
    | '/dashboard/creation'
    | '/dashboard/inbox'
    | '/dashboard/mail'
    | '/dashboard/observability'
    | '/dashboard'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/changelog'
    | '/dashboard'
    | '/docs'
    | '/pricing'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/sso-callback'
    | '/terms'
    | '/api/chat'
    | '/api/github-stars'
    | '/api/turnstile-verify'
    | '/dashboard/agents'
    | '/dashboard/board'
    | '/dashboard/bookmarks'
    | '/dashboard/calendar'
    | '/dashboard/creation'
    | '/dashboard/inbox'
    | '/dashboard/mail'
    | '/dashboard/observability'
    | '/dashboard/'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChangelogRoute: typeof ChangelogRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGithubStarsRoute: typeof ApiGithubStarsRoute
  ApiTurnstileVerifyRoute: typeof ApiTurnstileVerifyRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/observability': {
      id: '/dashboard/observability'
      path: '/observability'
      fullPath: '/dashboard/observability'
      preLoaderRoute: typeof DashboardObservabilityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mail': {
      id: '/dashboard/mail'
      path: '/mail'
      fullPath: '/dashboard/mail'
      preLoaderRoute: typeof DashboardMailRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inbox': {
      id: '/dashboard/inbox'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof DashboardInboxRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/creation': {
      id: '/dashboard/creation'
      path: '/creation'
      fullPath: '/dashboard/creation'
      preLoaderRoute: typeof DashboardCreationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookmarks': {
      id: '/dashboard/bookmarks'
      path: '/bookmarks'
      fullPath: '/dashboard/bookmarks'
      preLoaderRoute: typeof DashboardBookmarksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/board': {
      id: '/dashboard/board'
      path: '/board'
      fullPath: '/dashboard/board'
      preLoaderRoute: typeof DashboardBoardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agents': {
      id: '/dashboard/agents'
      path: '/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof DashboardAgentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/turnstile-verify': {
      id: '/api/turnstile-verify'
      path: '/api/turnstile-verify'
      fullPath: '/api/turnstile-verify'
      preLoaderRoute: typeof ApiTurnstileVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-stars': {
      id: '/api/github-stars'
      path: '/api/github-stars'
      fullPath: '/api/github-stars'
      preLoaderRoute: typeof ApiGithubStarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAgentsRoute: typeof DashboardAgentsRoute
  DashboardBoardRoute: typeof DashboardBoardRoute
  DashboardBookmarksRoute: typeof DashboardBookmarksRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardCreationRoute: typeof DashboardCreationRoute
  DashboardInboxRoute: typeof DashboardInboxRoute
  DashboardMailRoute: typeof DashboardMailRoute
  DashboardObservabilityRoute: typeof DashboardObservabilityRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgentsRoute: DashboardAgentsRoute,
  DashboardBoardRoute: DashboardBoardRoute,
  DashboardBookmarksRoute: DashboardBookmarksRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardCreationRoute: DashboardCreationRoute,
  DashboardInboxRoute: DashboardInboxRoute,
  DashboardMailRoute: DashboardMailRoute,
  DashboardObservabilityRoute: DashboardObservabilityRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChangelogRoute: ChangelogRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGithubStarsRoute: ApiGithubStarsRoute,
  ApiTurnstileVerifyRoute: ApiTurnstileVerifyRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
